### ISSUE TITLE
[FR] Option to keep the old icon

### ISSUE THREAD

**Issue by Hate9** [nullobsi/cantata#18]
Hey, would it be possible to have an option to re-enable the old Cantata icon? I've always really liked it, and I'm a bit sad to see it gone.

**Comment by nullobsi** [comment]
Are you talking about the GUI icons, or the actual application icon?

Since the desktop file has changed the KDE Breeze icon doesn't match anymore; you have to rename the icon to match dog.unix.cantata.Cantata.

However, since the GUI icons were migrated to a completely new framework based on FontAwesome 6, I cannot add an option to go back.
