### ISSUE TITLE
mpd access?

### ISSUE THREAD

**Issue by coffseducation** [nullobsi/cantata#2]
Hello!
Thanks for keeping this player alive!

When you open it however there is no local option -as it cannot see mpd.
Is there away to add this function so one can use with a local library?

Thanks!

Flatpak

**Comment by nullobsi** [comment]
I believe due to the limitations of Flatpak this might not be possible without installing MPD inside of the flatpak environment.

It can be something I could look into on the build scripts, so it's possible to use MPD "simple mode" as it's called in Cantata.

For now, I recommend running MPD locally outside of flatpak, and setting the music directory in Cantata.

**Comment by coffseducation** [comment]
Yes, "simple mode" or "Single User Mode" is what I meant.
Thanks for the clarification.
So, it is still possible to connect to mpd then without this mode? I will investigate.
Thanks!

**Comment by coffseducation** [comment]
ps. Would an appimage resolve the limitation?

**Comment by nullobsi** [comment]
An app-image has no sandboxing and might work, but I don't know the proper way to package a Qt application as an AppImage. For me Flatpak was a bit simpler to make. It's also possible to compile it yourself locally, if that's not too much of a problem. You could also use Flatpak overrides (--filesystem=host-os) and see if maybe that lets you use MPD from the host system.
